export type VideoModelId = "kling-3.0-omni" | "kling-3.0" | "seedance-2-5" | "seedance-2-0" | "seedance-2-0-fast" | "seedance-2-0-mini";
export type SeedanceVideoLine = "standard" | "backup";
export type VideoAspectRatio = "adaptive" | "16:9" | "9:16" | "1:1" | "4:3" | "3:4" | "21:9";
export type VideoGenerationType = "text_to_video" | "image_to_video" | "first_last_frame" | "reference_to_video" | "video_edit" | "video_extend" | "motion_control";
export type VideoResolution = "480p" | "720p" | "1080p" | "4k";
export type VideoGenerationCount = 1 | 2 | 4;
export type VideoRole = "first_frame" | "last_frame" | "refer_image" | "image" | "feature_video" | "base_video" | "video" | "reference_audio";
export type VideoMaterial = { kind: "image" | "video" | "audio"; assetKind: "reference" | "generated" | "video" | "audio"; assetId: string; name: string; role?: VideoRole };
export type VideoGenerationMedia = VideoMaterial & { role: VideoRole };
export type CanvasVideoGenerationDraft = { modelId: VideoModelId; type: VideoGenerationType; prompt: string; resolution: VideoResolution;
  duration: number; aspectRatio: VideoAspectRatio; audio: "native" | "original" | "off"; multiShot: boolean; characterOrientation: "video" | "image"; seedanceLine?: SeedanceVideoLine;
  shots: { seconds: number; text: string }[]; materials: VideoMaterial[]; roles: Record<string, VideoRole>; count?: VideoGenerationCount;
  requestId?: string; lastInput?: VideoGenerationInput; submissionError?: string };
export type VideoGenerationInput = Omit<CanvasVideoGenerationDraft, "materials" | "roles" | "requestId" | "lastInput" | "count" | "submissionError"> & { requestId: string; projectId: string; media: VideoGenerationMedia[]; quotedCredits?: number };
export type VideoGenerationState = "queued" | "submitting" | "submission_unknown" | "running" | "saving" | "save_failed" | "succeeded" | "failed";
export type VideoGenerationStatus = { requestId: string; state: VideoGenerationState; progress: number | null; reservedCredits: number; chargedCredits: number;
  output: null | { id: string; name: string; url: string; pixelWidth?: number; pixelHeight?: number; durationSeconds?: number }; error: null | { code: string; message: string; diagnostics?: Record<string, unknown> } };
export const VIDEO_GENERATION_MODELS: readonly { id: VideoModelId; name: string; resolutions: readonly VideoResolution[] }[];
export const VIDEO_GENERATION_TYPES: readonly { id: VideoGenerationType; name: string; modelId: VideoModelId; hint: string }[];
export const VIDEO_IMAGE_ROLES: readonly VideoRole[];
export const VIDEO_VIDEO_ROLES: readonly VideoRole[];
export const VIDEO_AUDIO_ROLES: readonly VideoRole[];
export const VIDEO_ROLE_LABELS: Record<VideoRole, string>;
export const VIDEO_ACTIVE_STATES: readonly VideoGenerationState[];
export const VIDEO_GENERATION_COUNTS: readonly VideoGenerationCount[];
export function defaultVideoGenerationDraft(): CanvasVideoGenerationDraft;
export function videoModelForType(type: string): VideoModelId | undefined;
export function videoTypeSupported(modelId: string, type: string): boolean;
export function videoRolesForType(type: VideoGenerationType, kind: "image" | "video" | "audio"): VideoRole[];
export function defaultVideoRole(type: VideoGenerationType, kind: "image" | "video" | "audio", index?: number): VideoRole | undefined;
export function videoGenerationProblem(input: Partial<VideoGenerationInput> & Pick<CanvasVideoGenerationDraft, "type" | "modelId" | "resolution" | "prompt">): string | null;
export function videoProviderBody(input: VideoGenerationInput, media: (VideoGenerationMedia & { url: string })[]): unknown;
