import type { Connection, Edge } from "@xyflow/react";
import type { CanvasNode } from "./canvas-workspace";
export const CANVAS_TEXT_MAX_LENGTH: number;
export const CANVAS_MARKDOWN_MAX_LENGTH: number;
export const CANVAS_PROMPT_MAX_LENGTH: number;
export const CANVAS_TEXT_FONT_SIZE: number;
export const CANVAS_TEXT_NODE_BOUNDS: Readonly<{ minWidth: number; minHeight: number; maxWidth: number; maxHeight: number }>;
export type CanvasTextInput = { edgeId: string; nodeId: string; text: string; markdown: string };
export function collectCanvasTextInputs(nodes: readonly CanvasNode[], edges: readonly Edge[], generatorId: string | null): CanvasTextInput[];
export function combineCanvasPrompt(inputs: readonly Pick<CanvasTextInput, "text">[], additionalPrompt: string): string;
export function canvasTextNodeSizeForKey(width: number | undefined, height: number | undefined, key: string, largeStep?: boolean): { width: number; height: number } | null;
export function canvasTextNodeFrameForKey(frame: { x: number; y: number; width?: number; height?: number }, corner: "top-left" | "top-right" | "bottom-left" | "bottom-right", key: string, largeStep?: boolean): { x: number; y: number; width: number; height: number } | null;
export function isCanvasTextConnection(connection: Connection | Edge, nodes: readonly CanvasNode[], edges: readonly Edge[]): boolean;
export function isCanvasTextGenerationConnection(connection: Connection | Edge, nodes: readonly CanvasNode[], edges: readonly Edge[]): boolean;
export function canvasConnectionCreatesCycle(connection: Connection | Edge, edges: readonly Edge[]): boolean;
export function normalizeCanvasInputEdge<T extends { sourceHandle?: string | null; targetHandle?: string | null }>(edge: T): T;
