export type PlacementPoint = Readonly<{ x: number; y: number }>;
export type PlacementSize = Readonly<{ width: number; height: number }>;
export type PlacementRegion = PlacementPoint & PlacementSize;
export type ImagePlacementView = PlacementPoint & Readonly<{ scale: number }>;
export type StickerPlacement = PlacementSize & Readonly<{ cx: number; cy: number; rotation: number }>;
export type PlacementCorner = "nw" | "ne" | "se" | "sw";
export const MAX_STICKER_LAYERS: number;
export const PLACEMENT_CORNERS: readonly PlacementCorner[];
export function imagePoint(point: PlacementPoint, view: ImagePlacementView): PlacementPoint;
export function fitImageView(size: PlacementSize, viewport: PlacementSize): ImagePlacementView;
export function zoomImageView(view: ImagePlacementView, scale: number, anchor: PlacementPoint): ImagePlacementView;
export function regionFromPoints(start: PlacementPoint, end: PlacementPoint, size: PlacementSize): PlacementRegion | null;
export function moveRegion(region: PlacementRegion, delta: PlacementPoint, size: PlacementSize): PlacementRegion;
export function resizeRegion(region: PlacementRegion, corner: PlacementCorner, point: PlacementPoint, size: PlacementSize): PlacementRegion;
export function regionCoordinates(region: PlacementRegion, size: PlacementSize, normalized?: boolean): number[];
export function regionPrompt(region: PlacementRegion, size: PlacementSize, normalized?: boolean): string;
export function defaultPlacement(sticker: PlacementSize, size: PlacementSize): StickerPlacement;
export function normalizeRotation(value: number): number;
export function placementCorner(layer: StickerPlacement, corner: PlacementCorner): PlacementPoint;
export function scalePlacement(layer: StickerPlacement, factor: number): StickerPlacement;
export function resizePlacement(layer: StickerPlacement, corner: PlacementCorner, point: PlacementPoint): StickerPlacement;
export function movePlacement(layer: StickerPlacement, delta: PlacementPoint, size: PlacementSize): StickerPlacement;
export function rotatePlacement(layer: StickerPlacement, start: PlacementPoint, point: PlacementPoint, snap?: boolean): StickerPlacement;
export function reorderPlacementLayers<T extends Readonly<{ id: string }>>(layers: readonly T[], id: string, delta: number): readonly T[];
export function paintStickerComposition(context: CanvasRenderingContext2D, base: CanvasImageSource, layers: readonly Readonly<{ resource: Readonly<{ image: CanvasImageSource }>; placement: StickerPlacement }>[]): void;
